# -------------------------
# Kafka
# -------------------------
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=console-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.properties.spring.json.trusted.packages=*

# -------------------------
# Elasticsearch (Spring Boot 3.3.4 + ES 8.x)
# -------------------------
# Optional: skip auto index creation during dev
spring.data.elasticsearch.client.create-index=false
