server:
  port: 8081

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true

spring:
  application:
    name: CITIZEN-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/citizendb
    password: password
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

    


