server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vaccinationcenterdb
    password: password
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true  

application:
    name: VACCINATION-CENTER-SERVICE
  


