server:
  port: 8082

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true  

spring:
  application:
    name: VACCINATION-CENTER-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3306/vaccinationcenterdb
    password: password
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect 


  


